schoolproject/schoolapp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from.import views

app_name='schoolapp'

urlpatterns = [
    path('',views.index,name='index'),
    path('register/',views.register,name='register'),
    path('login',views.login_view,name='login'),
    path('student_add', views.student_add, name='student_add'),
    path('load_courses/', views.load_courses, name='load_courses'),
    path('logout/',views.logout,name='logout'),
    path('confirm',views.confirm, name='confirm'),
 
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schoolproject/schoolproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('schoolapp.urls')),   
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schoolproject/schoolapp/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.
from django.db import models


class Department(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Courses(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


purpose = (
    ("1", "Enquiry"),
    ("2", "Place Order"),
    ("3", "Return"),
    ("4", "Feedback"),
    ("5", "Queries"),
)

materials_choices = (
                    ('Notebook', 'Notebook'), 
                    ('Pen', 'Pen'),
                    ('Exam Papers', 'Exam Papers'),
                    ('Books', 'Books'))
gender_choices = (('M', 'Male'), ('F', 'Female'))

class Student(models.Model):
    first_name = models.CharField( max_length=50)
    last_name = models.CharField(max_length=100)
    dob = models.CharField(max_length=50)
    age = models.CharField(max_length=3)
    email = models.EmailField()
    address = models.TextField()
    phoneNumber = models.CharField(max_length=12)
    gender_choices = (('M', 'Male'), ('F', 'Female'))
    gender = models.CharField(max_length=1, choices=gender_choices)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, blank=True, null=True)
    courses = models.ForeignKey(Courses, on_delete=models.SET_NULL, blank=True, null=True)
    purpose = models.CharField(max_length=15,choices=purpose)
    materials_choices = (('Notebook', 'Notebook'), ('Pen', 'Pen'), ('Exam Papers', 'Exam Papers'),
                     ('Books', 'Books'), )
    materials = models.CharField(max_length=15,choices=materials_choices)
    def __str__(self):
        return self.first_name

schoolproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="School Store">
	<meta name="author" content="webThemez.com">
<!--	<title>School Store</title>-->

<!--	<link rel="favicon" href="{% static 'assets/images/favicon.png' %}">-->
	<link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap-theme.css' %}" media="screen">
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel='stylesheet' id='camera-css'  href="{% static 'assets/css/camera.css' %}" type='text/css' media='all'>

	<title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
	{% include 'navbar.html' %}


    {% block content %}
    {% endblock %}
</div>
<br>
<div class="container">
    {% include 'footer.html' %}
</div>
</body>
 <!-- JAVASCRIPT
    ================================================== -->
    <script src="{% static 'https://code.jquery.com/jquery-3.3.1.min.js' %}"></script>
	<script src="{% static 'https://cdn.jsdelivr.net/npm/jquery@3.7.0/dist/jquery.min.js' %}"></script>
	<script src="../../../../../../../netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
	<script type='text/javascript' src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script type='text/javascript' src="{% static 'assets/js/fancybox/jquery.fancybox.pack.js' %}"></script>

    <script type='text/javascript' src="{% static 'assets/js/jquery.mobile.customized.min.js' %}"></script>
    <script type='text/javascript' src="{% static 'assets/js/jquery.easing.1.3.js' %}"></script>
    <script type='text/javascript' src="{% static 'assets/js/camera.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'assets/js/custom.js' %}"></script>
    <script>
		jQuery(function(){

			jQuery('#camera_wrap_4').camera({
                transPeriod: 500,
                time: 3000,
				height: '600',
				loader: 'false',
				pagination: true,
				thumbnails: false,
				hover: false,
                playPause: false,
                navigation: false,
				opacityOnGrid: false,
				imagePath: 'assets/images/'
			});

		});

	</script>


</body>


</html>

schoolproject/templates/confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirmation</title>
</head>
<body>
<h1>Your Order Successfully Placed</h1>
<a href="/" class="btn btn-primary"><span class="glyphicon glyphicon-log-in"></span>Home</a> 
<a href="{% url 'schoolapp:logout' %}">Log Out</a>
</body>
</html>

schoolproject/templates/courses_dropdown.html
<option value="">-----</option>
{% for course in courses %}
<option value="{{ course.pk }}">{{course.name}}</option>
{% endfor %}

schoolproject/templates/footer.html
{% load static %}
<footer id="footer">

		<div class="container">
   <div class="row">
  <div class="footerbottom">
    <div class="col-md-3 col-sm-6">
      <div class="footerwidget">
        <h4>
          Course Categories
        </h4>
        <div class="menu-course">
          <ul class="menu">
            <li><a href="#">
                List of Technology
              </a>
            </li>
            <li><a href="#">
                List of Business
              </a>
            </li>
            <li><a href="#">
                List of Photography
              </a>
            </li>
            <li><a href="#">
               List of Language
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-sm-6">
      <div class="footerwidget">
        <h4>
          Products Categories
        </h4>
        <div class="menu-course">
          <ul class="menu">
            <li> <a href="#">
                Individual Plans  </a>
            </li>
            <li><a href="#">
                Business Plans
              </a>
            </li>
            <li><a href="#">
                Free Trial
              </a>
            </li>
            <li><a href="#">
                Academic
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-sm-6">
      <div class="footerwidget">
        <h4>
          Browse by Categories
        </h4>
        <div class="menu-course">
          <ul class="menu">
            <li><a href="#">
                All Courses
              </a>
            </li>
            <li> <a href="#">
                All Instructors
              </a>
            </li>
            <li><a href="#">
                All Members
              </a>
            </li>
            <li>
              <a href="#">
                All Groups
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-sm-6">
            	<div class="footerwidget">
                         <h4>Contact</h4>
                        <p>Lorem reksi this dummy text unde omnis iste natus error sit volupum</p>
            <div class="contact-info">
            <i class="fa fa-map-marker"></i> Kerniles 416  - United Kingdom<br>
            <i class="fa fa-phone"></i>+00 123 156 711 <br>
             <i class="fa fa-envelope-o"></i> <a href="{% static 'https://demo.themezy.com/cdn-cgi/l/email-protection' %}" class="__cf_email__" data-cfemail="9be2f4eee9fef6faf2f7dbfef6faf2f7b5f8f4f6">[email&#160;protected]</a>
              </div>
                </div><!-- end widget -->
    </div>
  </div>
</div>
			<div class="social text-center">
				<a href="#"><i class="fa fa-twitter"></i></a>
				<a href="#"><i class="fa fa-facebook"></i></a>
				<a href="#"><i class="fa fa-dribbble"></i></a>
				<a href="#"><i class="fa fa-flickr"></i></a>
				<a href="#"><i class="fa fa-github"></i></a>
			</div>

			<div class="clear"></div>
			<!--CLEAR FLOATS-->
		</div>
		<div class="footer2">
			<div class="container">
				<div class="row">

					<div class="col-md-6 panel">
						<div class="panel-body">
							<p class="simplenav">
								<a href="">Home</a> |
								<a href="">About</a> |
								<a href="">Courses</a> |
								<a href="">Price</a> |
								<a href="">Videos</a> |
								<a href="">Contact</a>
							</p>
						</div>
					</div>

					<div class="col-md-6 panel">
						<div class="panel-body">
							<p class="text-right">
								Copyright &copy; SchoolStore .........
							</p>
						</div>
					</div>

				</div>
				<!-- /row of panels -->
			</div>
		</div>
	</footer>

schoolproject/templates/header.html
{% load static %}
<!-- Header -->
	<header id="head">
		<div class="container">
             <div class="heading-text">
							<h1 class="animated flipInY delay1">Start Online Education</h1>
							<p>Free Online education template for elearning and online education institute.</p>
						</div>

					<div class="fluid_container">
                    <div class="camera_wrap camera_emboss pattern_1" id="camera_wrap_4">
                        <div data-thumb="{% static 'assets/images/slides/thumbs/img1.jpg' %}" data-src="{% static 'assets/images/slides/img1.jpg' %}">
                            <h2>We develop.</h2>
                        </div>
                        <div data-thumb="{% static 'assets/images/slides/thumbs/img2.jpg' %}" data-src="{% static 'assets/images/slides/img2.jpg' %}">
                        </div>
                        <div data-thumb="{% static 'assets/images/slides/thumbs/img3.jpg' %}" data-src="{% static 'assets/images/slides/img3.jpg' %}">
                        </div>
                    </div><!-- #camera_wrap_3 -->
                </div><!-- .fluid_container -->
		</div>
	</header>
	<!-- /Header -->

schoolproject/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
   School Store-Learning Platform
{% endblock %}

 {% block content %}
<!-- Header -->
	<header id="head">
		<div class="container">
             <div class="heading-text">
							<h1 class="animated flipInY delay1">Start Online Education</h1>
							<p>Free Online education template for elearning and online education institute.</p>
						</div>

					<div class="fluid_container">
                    <div class="camera_wrap camera_emboss pattern_1" id="camera_wrap_4">
                        <div data-thumb="{% static 'assets/images/slides/thumbs/img1.jpg' %}" data-src="{% static 'assets/images/slides/img1.jpg' %}">
                            <h2>We develop.</h2>
                        </div>
                        <div data-thumb="{% static 'assets/images/slides/thumbs/img2.jpg' %}" data-src="{% static 'assets/images/slides/img2.jpg' %}">
                        </div>
                        <div data-thumb="{% static 'assets/images/slides/thumbs/img3.jpg' %}" data-src="{% static 'assets/images/slides/img3.jpg' %}">
                        </div>
                    </div><!-- #camera_wrap_3 -->
                </div><!-- .fluid_container -->
		</div>
	</header>
	<!-- /Header -->
  <div class="container">
    <div class="row">
					<div class="col-md-3">
						<div class="grey-box-icon">
							<div class="icon-box-top grey-box-icon-pos">
								<img src="{% static 'assets/images/1.png' %}" alt="" />
							</div><!--icon box top -->
							<h4>Online Courses</h4>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tempus eleifend risus ut congue
							eset nec lacus elit dor broma.</p>
     						<p><a href="#"><em>Read More</em></a></p>
						</div><!--grey box -->
					</div><!--/span3-->
					<div class="col-md-3">
						<div class="grey-box-icon">
							<div class="icon-box-top grey-box-icon-pos">
								<img src="{% static 'assets/images/2.png' %}" alt="" />
							</div><!--icon box top -->
							<h4>Meet our Staff</h4>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tempus eleifend risus ut congue
							eset nec lacus elit dor broma.</p>
     						<p><a href="#"><em>Read More</em></a></p>
						</div><!--grey box -->
					</div><!--/span3-->
					<div class="col-md-3">
						<div class="grey-box-icon">
							<div class="icon-box-top grey-box-icon-pos">
								<img src="{% static 'assets/images/3.png' %}" alt="" />
							</div><!--icon box top -->
							<h4>Latest Updates</h4>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tempus eleifend risus ut congue
							eset nec lacus elit dor broma.</p>
     						<p><a href="#"><em>Read More</em></a></p>
						</div><!--grey box -->
					</div><!--/span3-->
					<div class="col-md-3">
						<div class="grey-box-icon">
							<div class="icon-box-top grey-box-icon-pos">
								<img src="{% static 'assets/images/4.png' %}" alt="" />
							</div><!--icon box top -->
							<h4>Placements</h4>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tempus eleifend risus ut congue
							eset nec lacus elit dor broma.</p>
     						<p><a href="#"><em>Read More →</em></a></p>
						</div><!--grey box -->
					</div><!--/span3-->
				</div>
    </div>
      <section class="news-box top-margin">
        <div class="container">
            <h2><span>New Courses</span></h2>
            <div class="row">

                <div class="col-lg-4 col-md-4 col-sm-12">
                    <div class="newsBox">
                        <div class="thumbnail">
                            <figure><img src="{% static 'assets/images/news2.jpg' %}" alt=""></figure>
                            <div class="caption maxheight2">
                            <div class="box_inner">
                                        <div class="box">
                                            <p class="title"><h5>Developer</h5></p>
                                            <p>Lorem ipsum dolor sit amet, conc tetu er adipi scing. Praesent ves tibuum molestie lacuiirhs. Aenean.</p>
                                        </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12">
                    <div class="newsBox">
                        <div class="thumbnail">
                            <figure><img src="{% static 'assets/images/news3.jpg' %}" alt=""></figure>
                            <div class="caption maxheight2">
                            <div class="box_inner">
                                        <div class="box">
                                            <p class="title"><h5>Photography   </h5></p>
                                            <p>Lorem ipsum dolor sit amet, conc tetu er adipi scing. Praesent ves tibuum molestie lacuiirhs. Aenean.</p>
                                        </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12">
                    <div class="newsBox">
                        <div class="thumbnail">
                            <figure><img src="{% static 'assets/images/news4.jpg' %}" alt=""></figure>
                            <div class="caption maxheight2">
                           <div class="box_inner">
                                        <div class="box">
                                            <p class="title"><h5>Audio Editing</h5></p>
                                            <p>Lorem ipsum dolor sit amet, conc tetu er adipi scing. Praesent ves tibuum molestie lacuiirhs. Aenean.</p>
                                        </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>



      <section class="container">
      <div class="row">
      	<div class="col-md-8"><div class="title-box clearfix "><h2 class="title-box_primary">About Us</h2></div>
        <p><span>Perspiciatis unde omnis iste natus error sit voluptatem. Cum sociis natoque penatibus et magnis dis parturient montes ascetur ridiculus musull dui.</span></p>
        <p>Lorem ipsumulum aenean noummy endrerit mauris. Cum sociis natoque penatibus et magnis dis parturient montes ascetur ridiculus mus. Null dui. Fusce feugiat malesuada odio.</p><p>Lorem ipsumulum aenean noummy endrerit mauris. Cum sociis natoque penatibus et magnis dis parturient montes ascetur ridiculus mus. Null dui. Fusce feugiat malesuada odio.</p>
        <a href="#" title="read more" class="btn-inline " target="_self">read more</a> </div>


          <div class="col-md-4"><div class="title-box clearfix "><h2 class="title-box_primary">Up Coming Courses</h2></div>
            <div class="list styled custom-list">
            <ul>
            <li><a title="Snatoque penatibus et magnis dis partu rient montes ascetur ridiculus mus." href="#">Mathematics and Computer Science</a></li>
            <li><a title="Fusce feugiat malesuada odio. Morbi nunc odio gravida at cursus nec luctus." href="#">Mathematics and Philosophy</a></li>
            <li><a title="Penatibus et magnis dis parturient montes ascetur ridiculus mus." href="#">Philosophy and Modern Languages</a></li>
            <li><a title="Morbi nunc odio gravida at cursus nec luctus a lorem. Maecenas tristique orci." href="#">History (Ancient and Modern)</a></li>
            <li><a title="Snatoque penatibus et magnis dis partu rient montes ascetur ridiculus mus." href="#">Classical Archaeology and Ancient History</a></li>
            <li><a title="Fusce feugiat malesuada odio. Morbi nunc odio gravida at cursus nec luctus." href="#">Physics and Philosophy</a></li>
            </ul>
            </div>
         </div>
      </div>
      </section>

{% endblock %}


</body>


</html>

schoolproject/templates/login.html
{% extends 'base.html' %}
{% block content %}
<!-- PAGE TITLE
    ================================================== -->
    <header class="py-8 py-md-11" style="background-image: none;">
        <div class="container text-center py-xl-2">
            <h1 class="display-4 fw-semi-bold mb-0">Login</h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-scroll justify-content-center">
                    <li class="breadcrumb-item">
                        <a class="text-gray-800" href="#">
                            Home
                        </a>
                    </li>
                    <li class="breadcrumb-item text-gray-800 active" aria-current="page">
                        Login
                    </li>
                </ol>
            </nav>
        </div>
<!--        &lt;!&ndash; Img &ndash;&gt;-->
<!--        <img class="d-none img-fluid" src="...html" alt="...">-->
    </header>


    <!-- LOGIN
    ================================================== -->
    <div class="container mb-11" >
        <div class="row gx-0 ">
            <div class="col-md-7 col-xl-4 mx-auto">
                <!-- Login -->
                <h3 class="mb-6">Log In to Your  Account!</h3>
                
                <!-- Form Login -->
                <form class="mb-5" method="post" action="">
                    {% csrf_token %}
                    {{form.as_p}}

                    <!-- Submit -->
                    <input type="submit" value="Login"/>
                </form>
                

                <!-- Text -->
                <p class="mb-0 font-size-sm text-center">
                    Don't have an account? <a class="text-underline" href="{% url 'schoolapp:register' %}">Sign up</a>
                </p>
            </div>
        </div>
    </div>
{% endblock %}

schoolproject/templates/navbar.html
{% load static %}
<!-- Fixed navbar -->
	<div class="navbar navbar-inverse">
		<div class="container">
			<div class="navbar-header">
				<!-- Button for smallest screens -->
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
				<a class="navbar-brand" href="index.html">
					<img src="{% static 'assets/images/logo.png' %}" alt="Techro HTML5 template"></a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav pull-right mainNav">
					<li class="active"><a href="">Home</a></li>
					<li class="dropdown">
						<a href="schoolapp/department" class="dropdown-toggle" data-toggle="dropdown">Departments <b class="caret"></b></a>
						<ul class="dropdown-menu">
                            <li><a href="https://en.wikipedia.org/wiki/Computer_science_education">Computer Science</a></li>
							<li><a href="https://en.wikipedia.org/wiki/Bachelor_of_Commerce">Commerce</a></li>
							<li><a href="https://en.wikipedia.org/wiki/Earth,_Planets_and_Space">Earth and Space Sciences</a></li>
                            <li><a href="https://en.wikipedia.org/wiki/Biochemistry">Chemistry and Biochemistry</a></li>
                            <li><a href="https://en.wikipedia.org/wiki/University_Degree_Program">University Studies Program</a></li>
						</ul>
					</li>
					<li><a href="{% url 'schoolapp:register' %}">Register</a></li>
					<li><a href="{% url 'schoolapp:login' %}">Login</a></li>
					
                    
					<li><a href="courses.html">Courses</a></li>


				</ul>
			</div>
			<!--/.nav-collapse -->
		</div>
	</div>
	<!-- /.navbar -->

schoolproject/templates/register.html
{% extends 'base.html' %}
{% block content %}


<!-- PAGE TITLE
    ================================================== -->
    <header class="py-8 py-md-11" style="background-image: none;">
        <div class="container text-center py-xl-2">
            <h1 class="display-4 fw-semi-bold mb-0">Register</h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-scroll justify-content-center">
                    <li class="breadcrumb-item">
                        <a class="text-gray-800" href="#">
                            Home
                        </a>
                    </li>
                    <li class="breadcrumb-item text-gray-800 active" aria-current="page">
                        Register
                    </li>
                </ol>
            </nav>
        </div>
<!--        &lt;!&ndash; Img &ndash;&gt;-->
<!--        <img class="d-none img-fluid" src="...html" alt="...">-->
    </header>
<!-- REGISTER
    ================================================== -->
    <div class="container mb-11">
        <div class="row gx-0">
            <div class="col-md-7 col-xl-4 mx-auto">
                <!-- Register -->
                
                <!-- Form Register -->
                <form method="POST" autocomplete="off">
                    {% csrf_token %}
                        <!-- Username -->
                        {{form.as_p}}
                        <!-- Submit -->
                        <input type="submit" class="btn btn-success btn-lg"  value="Register"/>
    
                </form>
                
                <!-- Text -->
                <p class="mb-0 font-size-sm text-center">
                    Already have an account? <a class="text-underline" href="{% url 'schoolapp:login' %}">Log In</a>
                </p>
            </div>
        </div>
    </div>

{% endblock %} 

schoolproject/templates/requirements.html
{% extends 'base.html' %}
{% block content %}
<!-- PAGE TITLE
    ================================================== -->
    <header class="py-8 py-md-11" style="background-image: none;">
        <div class="container text-center py-xl-2">
            <h1 class="display-4 fw-semi-bold mb-0">Requirements Form</h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-scroll justify-content-center">
                    <li class="breadcrumb-item">
                        <a class="text-gray-800" href="#">
                            Home
                        </a>
                    </li>
                    <li class="breadcrumb-item text-gray-800 active" aria-current="page">
                        Requirements
                    </li>
                </ol>
            </nav>
        </div>

    </header>


    <!-- REQUIREMENT
    ================================================== -->
    <div class="container mb-11" >
        <div class="row gx-0 ">
            <div class="col-md-7 col-xl-4 mx-auto">
                <!-- Login -->
                <h3 class="mb-6">Requirement Form!</h3>

                <!-- Form Login -->
                
                <form class="mb-5" method="post" id="studentForm" data-courses-url="{% url 'schoolapp:load_courses' %}">
                    {% csrf_token %}
                        {{ form.as_p }}
                            
                            <button type="submit" class="btn btn-primary">Submit<a href="{% url 'schoolapp:confirm' %}"></a></button>
                          
                </form>
                {% if  request.user.is_authenticated %}
               <br>
                <button type="submit" ><a href="{% url 'schoolapp:logout' %}">Log Out</a></button>
                    
              {% endif %}
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    
    <script>
        $("#id_department").change(function () {
            const url = $("#studentForm").attr("data-courses-url");  
            const departmentId = $(this).val();  
    
            $.ajax({                       
                url: url,                   
                data: {
                    'department_id': departmentId       
                },
                success: function (data) {
                    console.log(data)   
                    $("#id_courses").html(data);  
                    
                }
            });
    
        });
    </script>

{% endblock %}